//ff:type feature=client type=model
//ff:what Types
import type { Hono } from '../hono'
import type { HonoBase } from '../hono-base'
import type { METHODS, METHOD_NAME_ALL_LOWERCASE } from '../router'
import type { Endpoint, ExtractSchema, KnownResponseFormat, ResponseFormat, Schema } from '../types'
import type { StatusCode, SuccessStatusCode } from '../utils/http-status'
import type { HasRequiredKeys } from '../utils/types'

export type { MethodNameAll } from './method_name_all.js'
export type { StandardMethods } from './standard_methods.js'
export type { ExpandAllMethod } from './expand_all_method.js'
export type { HonoRequest } from './hono_request.js'
export type { BuildSearchParamsFn } from './build_search_params_fn.js'
export type { ClientRequestOptions } from './client_request_options.js'
export type { ClientRequest } from './client_request.js'
export type { ClientResponseOfEndpoint } from './client_response_of_endpoint.js'
export type { BuildSearch } from './build_search.js'
export type { BuildPathname } from './build_pathname.js'
export type { BuildPath } from './build_path.js'
export type { BuildTypedURL } from './build_typed_url.js'
export type { HonoURL } from './hono_url.js'
export type { ParseHostName } from './parse_host_name.js'
export type { TrimStartSlash } from './trim_start_slash.js'
export type { TrimEndSlash } from './trim_end_slash.js'
export type { IsLiteral } from './is_literal.js'
export type { ApplyParam } from './apply_param.js'
export type { IsEmptyObject } from './is_empty_object.js'
export type { Fetch } from './fetch.js'
export type { InferEndpointType } from './infer_endpoint_type.js'
export type { InferResponseType } from './infer_response_type.js'
export type { InferResponseTypeFromEndpoint } from './infer_response_type_from_endpoint.js'
export type { InferRequestType } from './infer_request_type.js'
export type { InferRequestOptionsType } from './infer_request_options_type.js'
export type { FilterClientResponseByStatusCode } from './filter_client_response_by_status_code.js'
export type { PathToChain } from './path_to_chain.js'
export type { Client } from './client_def.js'
export type { Callback } from './callback.js'
export type { ObjectType } from './object_type.js'
export type { GlobalResponseDefinition } from './global_response_definition.js'
export type { ToEndpoints } from './to_endpoints.js'
export type { ModRoute } from './mod_route.js'
export type { ModSchema } from './mod_schema.js'
export type { ApplyGlobalResponse } from './apply_global_response.js'
export type { PickRoute } from './pick_route.js'
export type { PickSchema } from './pick_schema.js'
export type { PickResponseByStatusCode } from './pick_response_by_status_code.js'
export type { ClientResponse } from './client_response.js'
export type { TypedURL } from './typed_url.js'
export type { Response } from './response.js'


export interface CallbackOptions {
  path: string[]
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  args: any[]
}
